platform :ios, '9.3'
use_frameworks!

def common
    pod 'MaterialActivityIndicator', :path => '../'
    pod 'SwiftLint'
end

target 'MaterialActivityIndicator_Example' do
    common
end

target 'MaterialActivityIndicatorTV_Example' do
    common
end
